#
# 这个文档包含了本博客的设定信息，你可以编辑它来个性化自己的博客，
#

# 你的博客名称，请用你想要的博客名替换“LOFFER”，以下修改都可类似处理
# 注意，“name: LOFFER”，冒号后面的空格不可以省略。
# 井号后面的文字是说明文档，不会被程序读取。

# 描述/签名
name: 鸭鸭文仓
description: 六只盐水鸭的文章仓库=3快乐吃粮

# 输入你的网站域名（如果你没有添加自己的域名，而是直接用GitHub pages分配的域名的话可以省略）
url: 

# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
baseurl: /DuckyFood


#
# 下面的设定都是可选的
#

# 你的博客logo图片URL，建议尺寸不超过300px × 300px
avatar: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwoJCAgJCQkICAgICA0JCAgICBAIFQcNIB0iIiAdHx8kKDQsJCYxJx8TLTEtMTU3Ojo6Fys/ODMsNyg5LisBCgoKDg0OGxAQGy0fICErLS0tLSstLy0tLi0tLy0rNS0rLS01LTg3OC04LS0rLS0tLS0wLSstLS03LS0rLS0tLf/AABEIAJYAlgMBIgACEQEDEQH/xAAbAAABBQEBAAAAAAAAAAAAAAAAAQIDBAUGB//EADoQAAEDAgQFAgMFBQkAAAAAAAEAAgMEEQUSITEGE0FRYXGBFCOhIjJCkdEzUmJysQckNDV0wcLw8f/EABkBAAMBAQEAAAAAAAAAAAAAAAABAgMEBf/EACQRAAIDAAIBBAIDAAAAAAAAAAABAgMREiExIkFRcQSxEzJh/9oADAMBAAIRAxEAPwDNw8j7YvZxI08K8sW/UXBHUKVlTLoA4k30G91xzr16TZS5PUaqEy7sgOUl2W+S3VUpa0lpaGljibE32WSg2YKmb9iSpqQ1zMli5js1+ye7FnuY5vLaCWkZgTosy17pwWv8UX5R6FM5VR4xYlkvRC06Smwx8LHVOI1UE5vnijw0ThmulnZ+1j7rVCM2yUC+gXUx8M4e+so6NuK1PProYpoL4WLZXC4uc+hsmx4ThkOcjEKqWRoORj8ODLuG2ufTVDWAjHpKEkh8lwAdGW3WmLCwGgGwVqgpPicwE9LAQWgNqJeWZCe2hvt9QtODBYonVcVZVUDJOS5sR+KcHU8txuNNN7+qjHIcpKCMG+6Rar8FeyNshrMODJM2R3xJ+bbsbdLhUqam58hZzYIAGF2eok5bfzt5TUTntt1YVrpzdvVb1HgsMM8Yr6nDzBJGSQKpzCARo4aDx4KrjAn5DIKzDjC14jMgqTYOOoF7b2Cvizlkm3plAJwCdIzI97MzH5Hludjrh9uxU8lI9lLDVEt5U8j42gE3BHcW226pGZXQlshAtOWIUtG7JPETaweL3SPjcw/aaWnyEy2t+qTWrD1100zqbDU6X7rmJznke7YF5ICtDEp8mS7SMuW+Xoq8ETpZGRs1c92ULnpqdeuR1/k3xuxRIwEFbA4fm6yxg9gCtuT+zuu5IkiqKeRxjz8ogs9rrau2Nn9Hpz20zqzms04xdHgNc1mHSUbaysw+ofXioEtLAZeZHltYnMOuvssqfCaumqORUQSQPG+dulvBXa8NVuKQ/DARYlW0ULAxkUTSxttt7eO/utN7Ms1F+Wt+CrqF9TiGI/IpKcTUpiJFQcu5GbQnqLX7rNqcSjdRYhC6ura19UIxCyeAsENn3OuYrakdPzmOlx2WjZJJeSkqeUySMb6WNh4KzsZxHGQ580fxENCG5Y3RPbUNLNrlw79TdDBYjHw9lG6M/ER4hJKHnWlcwNA08Hytrl0WJSOMkWKskpqFz3SExA1DWDS5tq49/Cz8BdPEySY1slBh7H/PdFIA6oePwtHcj9StehrcRea6rJrosPOHzyUr55C8NOX7NieqIo5rLOb/AMKNfU0NU6LNTYtHHBE2KGGIxhsTR20PXU91nUraJz5uZHiDm5/kCB0dwzX71wfGy1aXEp6ynbHHidVS4gwWEdRUHJXdrHTKVnYK2p50z4qsULGD+91Rkty2n31JI0HVMxb1mpAKKvNDQvixVojc6OGZ/Kuxp1sTbbt6qKeegkp4KcUuLRwwXIbGY/mvPV1xqen9FoYdV11RiNPJTvxCTC435JJ55C4TW3J7XVDD8XlnjfDNiVXS1ZdeCofMTG/+F2mnr51VDMSqEQmeIBM2IEBjagguHroPK0aj/JMP/wBbUf8AFUa1soqZhUOzzh5Er84kzu9Rup5mOGHUrjPG5nxEmSnAGaE6anrbQLMy+SmhCEiCo9jXaOAcD0IVSegY65YSw9t1dQQkelCzwmYstLJHe4uB1bqo4pHRua9hLXNN2uHQrdI9wq8tJG++mR3dqN+TZfKLWDY+1lRCK9pdC14zyMGtvIXq9I2nneK6nkMgkhbGHMlJaWjbReLMw+zjmcHNGwAtddfwE6RmItijc5kBje6SMONj209UUxhB+lZpV052JOT3DquLqBlVh0zyGianbzGPt0H6hedmtqBE2IVE/JbcNh5rsovvYX7lencRStiw2scSBeBzG36k7f1XlU2jRte6u3yZ1jxJfwU9k8rGvYySRrJRlkYx5AkHkKtB94+ila0kgAEknQAXus0iPyJ+lpAnmaQsEZkkMY2YXmw9tlp0vDtfUAObTuY07OkIj/qrEnCWINFwyN+mzXi/1WmM4eLMQD8k4D6qaoop6Z/LnjfG4dHjf07qNIjwPbLI1hYJJAx27A8gH2TbJE5AmKhCQFIQqEIQBVuluhIg3jLZL7JANlGXDM4DTKLovcHvlKY5v5lgBUJHfOaXQ/oPK7zgnDRT05qngCSoFo/4GLlMEwp+I1QibdsMQBmkt9wfqV6XZsMIAsGRR2A7Ba1x9yHNyRy3HOI6R0TDrcSTW+g/3XFuAdp0VvEqp1TVTyuJJkeSL9B0+ighhfK9scbHPe51mtaL3KUu2c8rusiWsBwaSvqeWw5YwLySEfs2r0PC8BpKIDlxh8gGssgzklRcM4WcPpix9nTSOzyEDZbK0jHDTt9sAEqRCsorVtDBVxmOeNrwRYOtq30K4bHuHpaEmSO8tMTo4amPwf1XoSRzQ4EEAgixBFwUmkyJQUjyJOB0Xc4xwrFUEyUxbBKdXMy/ZeVyFdh1RRvLJ43NA2eBcH0KyccOadbRVukuhCkzHXQm2QmBAEKXIkLEFJ49Imt38iyeG6DqQLJcqfAx0kscbRd0jwxo7nZJIuVkpvs9H4dpG0+HUwa3K6SMSSG333HVXZ2Z2PZqA9papaeLJDEzbIxrbDpolc33W6OpeDh6jhGcS/KljdGXal/2CwLosHwWChALRmmI+3K7f27BahCQBHFEqCT0lanJkZTwUywQhCABCEIAEyaFkrCyRjZGndr23BT0IA52s4Upn3fTl0L73yOOdpWJV4VJSkCaIAHZ7RcH3XeqniVXBBE4TkEPY4NZlvzPRS4iSSOGETR+EfkhPNtegvohZlYYttEiek091J5wyyt4OQMQoy61hUMJVYhEbix7XjQtcHD1CaGn2etgJVWw+p+IpoJgLCWMOPg9fqrK3O9DC1RkKZwUbggBGlPBUaUHVAEwQs3FsTjoKczPBcS4NjYDYvKpM4uoCDczNcNmmM6o0Tkkb6Fj4lj9LBSOkjnjfM5nymMcHnN5HZRYXxNSzwB1RK2CZgs9rzYE+O6WhyRuot4WI/ivDm5rSyPLdg2I/b9FkO40eJZMlOHQk/LDn2I9UckS5xXudfLNHEAZHtjDjYF7gLlczxLVwzvhbE8SGMOL3MN7X6XWDXY1PX1DHSWYwGzI2/g/VKpcioSUu0PBSprevqhQWZF00lOKSyk80S6RCLJjO44IrDJSyU7jc07rs/lP/SumXA8FVHLxEx7CaJzfff8AVd8tYvo663sRHDRNT1C+472VGg4Ae6CPzTBupLgXOg7koAzsVwqKvjayXOCwksew2LCubrOEHxMkkjqA8MaXBr2ZLj1uugruIqGlzNMvNkH4Ihn19VyGM8R1FbmjYTBTk/s2HV48lS8MZuHuYp0SB3smjVOyrI5hwPulSNCW6AHxmzmnazlrArHDtvBWqwktB7gJo6aH0yVhQmhCDoMspqckUnmDUO6JU0lAy/gEhjxKkcNCZg0+my9PGy8swf8Ax9J4qGL1Jq1h4OqnwKq2I1LKamlmktljYXam1z0VlYXGU7I8Lla/V0zhHGO7v/AqZq3iMGbjKUg8mnjYf3pHl/00WRWY7XVILZJ3tYd2R/Lv62WaELJybORzkwuhCcAkQA9wnIQgAQhLZMBLLWgPy2fyhZKswT5W5SbWQbUySfZooVT4kfvBImdPKPyVt0lktkl1B54iQpUEJjJKOXlVEMmto5GuPoF6nDUxStjLJGu5jczAHDULye3sU+KeSJ7XxvexzDdrmuIsnGWGtc8eM9ae9rAS4hgH4nGy4Di+sNVPZjy6mgNmDu7qQqFdjNXVsjZNJmbHsALAnz3We8uO5Jvus5ysk1nS/Z2OyiMHvqbX0kRAeqXKVI0d0qs84YGpUpQEACSyfbwgBAhoBS2T7JUg0jyoyKRCA0jshLZKmMckSoSJGlCEIGB6JvdCEAgQhCYxUqEIAYUDcIQgB90t0ISEF0IQgQqEIQAIQhAH/9k=

# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkwkA4qDxYx69GbwNKXepwy2iZn235TExezw&usqp=CAU


# 菜单中的按钮
navigation:
  - name: 首页
    url: /
  - name: 简介
    url: /about
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags

# 每页的文章数
paginate: 8

# 文章简介的区分标记
excerpt_separator: <!-- more -->

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links: 
  weibo:  #请输入你的微博个性域名 https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<>
  dribbble: # https://dribbble.com/<>
  email: #youremailaddress@mail.com
  facebook: #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: FromEndWorld/loffer #https://github.com/<>
  instagram: #https://instagram.com/<>
  linkedin: #https://www.linkedin.com/in/<>
  pinterest: #https://www.pinterest.com/<>
  rss: #随便填点啥RSS就能用了
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  twitter: # https://www.twitter.com/<your_twitter_username> 
  youtube: # channel/<your_long_string> or user/<user-name>

# 站点页脚的文字
footer-text: Copyright (c) 2023 来自六只盐水鸭

#
# 评论，注意，请不要同时添加多种不同的评论区
#

# 输入Disqus shortname，即可添加评论区，请查阅文档，设置自己的disqus站点，不要继续使用我的站点loffer
disqus: loffer #shortname

# 输入Gitalk相关设定，即可添加评论区，具体请看教程
gitalk:
  clientID: 
  clientSecret: 
  repo: 
  owner: 
  proxy:

# 输入Google Analytics web tracking code
google_analytics:

utteranc:
  repo: # Your github repo path, also see: https://utteranc.es

#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

